config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("diary.urls", namespace="diary")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from diary.apps import DiaryConfig
from diary.views import (EntryCreateView, EntryDeleteView, EntryDetailView,
                         EntryListView, EntrySearchView, EntryUpdateView,
                         Index)

app_name = DiaryConfig.name

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("entries/", EntryListView.as_view(), name="entry_list"),
    path("entry/create/", EntryCreateView.as_view(), name="entry_create"),
    path("entry/update/<int:pk>/", EntryUpdateView.as_view(), name="entry_update"),
    path(
        "entry/detail/<int:pk>/",
        cache_page(30)(EntryDetailView.as_view()),
        name="entry_detail",
    ),
    path("entry/delete/<int:pk>/", EntryDeleteView.as_view(), name="entry_delete"),
    path("search/", EntrySearchView.as_view(), name="entry_search"),
]

diary/models.py
from django.db import models
from django.utils import timezone

from config import settings

NULLABLE = {"null": "True", "blank": "True"}
USER = settings.AUTH_USER_MODEL


class Entry(models.Model):
    title = models.CharField(max_length=200, verbose_name="Title")
    text = models.TextField(verbose_name="Text")
    image = models.ImageField(
        upload_to="diary_images/", verbose_name="Image", **NULLABLE
    )
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Date")
    is_public = models.BooleanField(default=False, verbose_name="Public")
    owner = models.ForeignKey(
        USER, on_delete=models.SET_NULL, verbose_name="Owner", **NULLABLE
    )

    # tag = models.CharField(max_length=50, verbose_name='Tag', **NULLABLE)

    def __str__(self):
        return f'"{self.title}" (added: {self.created_at})'

    class Meta:
        verbose_name = "entry"
        verbose_name_plural = "entries"
        ordering = ("created_at",)


# class Comment(models.Model):
#     entry = models.ForeignKey(Entry, on_delete=models.CASCADE, related_name='comments')
#     text = models.TextField()
#     created_at = models.DateTimeField(auto_now_add=True)
#
#     def __str__(self):
#         return f'Comment on {self.entry}: {self.text[:20]}...'

diary/forms.py
from django import forms
from django.forms import BooleanField

from diary.models import Entry


class StyleFormMixin(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input rounded"
            else:
                field.widget.attrs["class"] = "form-control rounded"


class EntryForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Entry
        # fields = '__all__'
        exclude = ("created_at", "owner")

diary/views.py
import random

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView)

from diary.forms import EntryForm
from diary.models import Entry
from diary.services import get_cache_for_entries_count


class Index(TemplateView):
    model = Entry
    template_name = "diary/index.html"
    extra_context = {
        "slogan": "Memont - memorize your moments.",
        "intro_text": "Be inspired by 'memonts' from community:",
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["total_entries_count"] = get_cache_for_entries_count
        context_data["public_entries_count"] = Entry.objects.filter(
            is_public=True
        ).count()
        context_data["personal_entries_count"] = Entry.objects.filter(
            is_public=False
        ).count()
        public_entries_list = list(Entry.objects.filter(is_public=True))
        random.shuffle(public_entries_list)
        context_data["public_entries_list"] = public_entries_list[:3]
        return context_data


class EntryListView(LoginRequiredMixin, ListView):
    model = Entry
    context_object_name = "entry_list"
    template_name = "diary/entry_list.html"

    def get_queryset(self):
        return Entry.objects.filter(owner=self.request.user)


class EntrySearchView(LoginRequiredMixin, ListView):
    model = Entry
    context_object_name = "entry_list"
    template_name = "diary/search_entries_list.html"

    def get_queryset(self):
        query = self.request.GET.get("query", "")
        if query:
            # Фильтруем записи по вхождению текста в заголовок или текст записи
            return Entry.objects.filter(
                Q(title__icontains=query) | Q(text__icontains=query),
                owner=self.request.user,
            )
        return Entry.objects.none()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["query"] = self.request.GET.get("query", "")
        return context


class EntryCreateView(LoginRequiredMixin, CreateView):
    model = Entry
    form_class = EntryForm
    success_url = reverse_lazy("diary:entry_list")
    extra_context = {"title": "Create entry"}

    def form_valid(self, form):
        new_entry = form.save(commit=False)
        new_entry.owner = self.request.user
        new_entry.save()
        return super().form_valid(form)


class EntryDetailView(LoginRequiredMixin, DetailView):
    model = Entry


class EntryUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Entry
    form_class = EntryForm
    success_url = reverse_lazy("diary:entry_list")
    extra_context = {"title": "Edit entry"}

    def test_func(self):
        entry = self.get_object()
        if self.request.user.is_staff:
            return True
        return self.request.user == entry.owner


class EntryDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Entry
    success_url = reverse_lazy("diary:entry_list")

    def test_func(self):
        entry = self.get_object()
        if self.request.user.is_superuser:
            return True
        return self.request.user == entry.owner

diary/templates/diary/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="dark">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Memont</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
    <link href="{% static 'favicon.png' %}" rel="icon" type="image/x-icon">
    <style>
        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }
        main {
            flex: 1;
        }
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }
        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
        .b-example-divider {
            width: 100%;
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }
        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }
        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }
        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }
        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }
        .btn-bd-primary {
            --bd-violet-bg: #712cf9;
            --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

            --bs-btn-font-weight: 600;
            --bs-btn-color: var(--bs-white);
            --bs-btn-bg: var(--bd-violet-bg);
            --bs-btn-border-color: var(--bd-violet-bg);
            --bs-btn-hover-color: var(--bs-white);
            --bs-btn-hover-bg: #6528e0;
            --bs-btn-hover-border-color: #6528e0;
            --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
            --bs-btn-active-color: var(--bs-btn-hover-color);
            --bs-btn-active-bg: #5a23c8;
            --bs-btn-active-border-color: #5a23c8;
        }
        .bd-mode-toggle {
            z-index: 1500;
        }
        .bd-mode-toggle .dropdown-menu .active .bi {
            display: block !important;
        }
        .btn.rounded {
            border-radius: 2rem !important;
        }
        .rounded {
            border-radius: 2rem !important;
        }
        .form-control {
            border-radius: 2rem !important;
        }
        .card {
            border-radius: 2rem !important;
        .card-header {
            border-top-left-radius: 2rem !important;
            border-top-right-radius: 2rem !important;
    </style>
</head>

<body>
<header data-bs-theme="dark">
    {% include 'diary/includes/nav_bar.html' %}
</header>

<main>
    <div class="content" style="margin-top: 60px;">
        {% block content %}
        {% endblock %}
    </div>
</main>

<footer class="container d-flex justify-content-between align-items-center mt-3">
    <p class="mb-1">
        <a href="https://sky.pro/" target="_blank" rel="noopener noreferrer">Skypro</a>
    </p>
    <p class="mb-1">
        &copy; {% now 'Y' %} Memont
    </p>
    <p class="mb-1 float-end">
        <a href="#">Back to top</a>
    </p>
</footer>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
</body>
</html>

diary/templates/diary/entry_confirm_delete.html
{% extends 'diary/base.html' %}

{% block content %}
<div class="d-flex align-items-center justify-content-center" style="height: 50vh; padding: 20px;">
    <div class="card w-25">
        <div class="card-body text-center mt-3">
            <form method="post">
                {% csrf_token %}
                <p>Are you sure you want to delete this entry "{{ object.title }}"?</p>
                <button type="submit" class="btn btn-danger rounded w-25 mt-2 mb-2 me-2">Delete</button>
                <a href="{% url 'diary:entry_detail' object.pk %}" class="btn btn-outline-secondary rounded w-25 mt-2 mb-2 ms-2">Cancel</a>

            </form>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/diary/entry_detail.html
{% extends 'diary/base.html' %}
{% load my_tags %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-4 offset-4">
            <div class="card">
                <div class="card-header">
                    <h6 class="my-0 font-weight-normal text-center">{{ entry.title }}</h6>
                </div>
                {% if entry.image %}
                <img class="card-img-top" src="{% my_media_tag entry.image %}" alt="Card image cap">
                {% endif %}
                <div class="card-body">
                    <p>{{ entry.text }}</p>
                    <div class="d-flex justify-content-center">
                        <div class="d-flex justify-content-center" style="width: 100%;">
                            {% if user.is_superuser or user == entry.owner %}
                            <a href="{% url 'diary:entry_update' entry.pk %}" type="button"
                               class="btn btn-outline-secondary rounded w-25 me-3">Edit</a>
                            <a href="{% url 'diary:entry_delete' entry.pk %}" type="button"
                               class="btn btn-outline-secondary rounded w-25 me-3">Delete</a>
                            {% endif %}
                            <a href="#" type="button"
                               class="btn btn-outline-secondary rounded w-25">Comment</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/diary/entry_form.html
{% extends 'diary/base.html' %}

{% block content %}
<div class="col-12">
    <div class="card col-4 offset-4">
        <div class="card-header rounded-top">
            <h5 class="card-title text-center">{{ title }}</h5>
        </div>
        <div class="card-body" style="padding: 20px;">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="text-center">
                    {% if object %}
                    <button type="submit" class="btn btn-outline-secondary rounded w-25">Save</button>
                    {% else %}
                    <button type="submit" class="btn btn-outline-secondary rounded w-25">Create</button>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/diary/entry_list.html
{% extends 'diary/base.html' %}
{% load my_tags %}

{% block content %}
<style>
    .row {
        display: flex; /* Используем Flexbox для размещения карточек */
        flex-wrap: wrap; /* Позволяем карточкам переноситься на следующую строку */
    }

    .custom-col {
        display: flex; /* Используем Flexbox внутри колонки */
        flex-direction: column; /* Устанавливаем вертикальное размещение элементов */
        justify-content: stretch; /* Позволяем карточкам занимать всю доступную высоту */
        padding: 1rem; /* Устанавливаем отступы между карточками */
    }

    .card {
        transition: background-color 0.3s ease, color 0.3s ease; /* Плавный переход */
        height: 100%; /* Устанавливаем фиксированную высоту карточки */
        width: 100%; /* Устанавливаем ширину на 100% */
        box-sizing: border-box; /* Учитываем отступы и границы в ширине */
    }

    .card:hover {
        background-color: #343a40; /* Цвет фона при наведении (темный) */
        color: white; /* Цвет текста при наведении (белый) */
    }

    .card-link {
        text-decoration: none; /* Убираем подчеркивание текста */
        color: inherit; /* Убираем изменение цвета текста по умолчанию */
        height: 100%; /* Устанавливаем высоту на 100% */
    }

    .card-body {
        display: flex;
        flex-direction: column; /* Устанавливаем вертикальное размещение элементов */
        flex-grow: 1; /* Позволяем телу карточки занимать доступное пространство */
    }

    .icon-small {
        font-size: 0.75rem; /* Уменьшаем размер иконки */
    }
    .highlight {
        background-color: rgba(180, 210, 250, 0.5); /* Полупрозрачный синий цвет для подсветки поиска */
    }
</style>

<div class="container-fluid">
    <div class="row mb-4 text-center">
        {% for entry in entry_list %}
        {% if entry.owner == user or user.is_staff %}
        <div class="col-md-3 custom-col d-flex">
            <a href="{% url 'diary:entry_detail' entry.pk %}" class="card-link">
                <div class="card mb-2 rounded-5 shadow-sm" style="overflow: hidden;">
                    <div class="card-header py-3" style="border-radius: 0.5rem 0.5rem 0 0;">
                        <h6 class="my-0 fw-normal text-uppercase">{{ entry.title|highlight:query|safe }}</h6>
                    </div>
                    <div class="card-body">
                        <h6 class="card-title pricing-card-title"
                            style="font-size: 0.95rem; font-weight: normal;
                            text-align: left; margin: 0 0 1rem 0; text-indent: 1rem;">
                            {{ entry.text|highlight:query|slice:':201'|safe }} ...</h6>
                        <ul class="list-unstyled mt-2 mb-2" style="font-size: 0.9rem;">
                            <li>Author: {{ entry.owner }}</li>
                        </ul>
                        <div class="d-flex justify-content-between mt-3">
                            <span class="text-muted small">Added at {{ entry.created_at }}</span>
                            <span class="text-muted small">
                                Public:
                                {% if entry.is_public %}
                                    <i class="far fa-check-circle icon-small"></i>
                                {% else %}
                                    <i class="far fa-times-circle icon-small"></i>
                                {% endif %}
                            </span>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% endif %}
        {% empty %}
        <p>No entries found.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

diary/templates/diary/index.html
{% extends 'diary/base.html' %}
{% load my_tags %}

{% block content %}
<div class="d-flex flex-column align-items-center justify-content-center" style="height: 25vh; text-align: center;">
    <div class="text-center"
         style="font-size: 2rem; font-family: 'Lato', sans-serif; font-weight: 300;">
        {{ slogan }}
        <br>
        {{ intro_text }}
    </div>
</div>
<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-5 text-center">
        {% for entry in public_entries_list %}
        <div class="col">
            <div class="card rounded-3 shadow-sm h-100">
                <div class="card-header py-3">
                    <h5 class="my-0 fw-normal text-uppercase">{{ entry.title }}</h5>
                </div>
                <div class="card-body d-flex flex-column">
                    <ul class="list-unstyled mt-2 mb-2">
                        <li class="mb-3">{{ entry.text|slice:':201' }} ...</li>
                        <li><span class="text-muted small">{{ entry.owner }}</span></li>
                        <li><span class="text-muted small">Added at {{ entry.created_at }}</span></li>
                    </ul>
                    <div class="mt-auto">
                        <a class="btn btn-outline-secondary rounded w-50 m-2"
                           href="{% url 'diary:entry_detail' entry.pk %}">View</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class="container mt-5">
    <div class="row text-start justify-content-center">
        <div class="col-3">
            <div class="p-1 mb-4 rounded text-body-emphasis bg-body-secondary">
                <p class="text-center my-1 small text-muted">
                    TOTAL ENTRY'S COUNT - <b>{{ total_entries_count|default:0 }}</b><br>
                    <b>({{ public_entries_count|default:0 }}</b> PUBLIC /
                    <b>{{ personal_entries_count|default:0 }}</b> PERSONAL)</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/diary/search_entries_list.html
{% extends 'diary/base.html' %}
{% load my_tags %}

{% block content %}
{% include 'diary/includes/entries_list_style.html' %}
<div class="container-fluid">
    <div class="row mb-4 text-center">
        {% for entry in entry_list %}
        <div class="col-md-3 custom-col d-flex">
            <a href="{% url 'diary:entry_detail' entry.pk %}" class="card-link">
                <div class="card mb-2 rounded-5 shadow-sm" style="overflow: hidden;">
                    <div class="card-header py-3" style="border-radius: 0.5rem 0.5rem 0 0;">
                        <h6 class="my-0 fw-normal text-uppercase">{{ entry.title|highlight:query|safe }}</h6>
                    </div>
                    <div class="card-body">
                        <h6 class="card-title pricing-card-title"
                            style="font-size: 0.95rem; font-weight: normal;
                                   text-align: left; margin: 0 0 1rem 0; text-indent: 1rem;">
                            {{ entry.text|highlight:query|safe }}...</h6>
                        <ul class="list-unstyled mt-2 mb-2" style="font-size: 0.9rem;">
                            <li>Author: {{ entry.owner }}</li>
                        </ul>
                        <div class="d-flex justify-content-between mt-3">
                            <span class="text-muted small">Added at {{ entry.created_at }}</span>
                            <span class="text-muted small">
                                Public:
                                {% if entry.is_public %}
                                    <i class="far fa-check-circle icon-small"></i>
                                {% else %}
                                    <i class="far fa-times-circle icon-small"></i>
                                {% endif %}
                            </span>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% empty %}
        <div class="empty-message-container">
            <p>No entries found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}