config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("diary.urls", namespace="diary")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from diary.apps import DiaryConfig
from diary.views import (EntryCreateView, EntryDeleteView, EntryDetailView,
                         EntryListView, EntrySearchView, EntryUpdateView,
                         Index)

app_name = DiaryConfig.name

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("entries/", EntryListView.as_view(), name="entry_list"),
    path("entry/create/", EntryCreateView.as_view(), name="entry_create"),
    path("entry/update/<int:pk>/", EntryUpdateView.as_view(), name="entry_update"),
    path(
        "entry/detail/<int:pk>/",
        cache_page(30)(EntryDetailView.as_view()),
        name="entry_detail",
    ),
    path("entry/delete/<int:pk>/", EntryDeleteView.as_view(), name="entry_delete"),
    path("search/", EntrySearchView.as_view(), name="entry_search"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.forms import LoginCustomForm
from users.views import (LoginRequiredTemplateView, ProfileView,
                         RegisterMessageView, UserCreateView,
                         UserPasswordRecoveryView, UserPasswordSentView,
                         confirm_register)

app_name = UsersConfig.name

urlpatterns = [
    path(
        "login/",
        LoginView.as_view(template_name="users/login.html", form_class=LoginCustomForm),
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("login_required/", LoginRequiredTemplateView.as_view(), name="login_required"),
    path("register/confirm/<str:code>/", confirm_register, name="confirm_register"),
    path("register/message/", RegisterMessageView.as_view(), name="register_message"),
    path(
        "user_password_sent/", UserPasswordSentView.as_view(), name="user_password_sent"
    ),
    path("password_reset/", UserPasswordRecoveryView.as_view(), name="password_reset"),
    path("profile/", ProfileView.as_view(), name="profile"),
]

diary/models.py
from django.db import models
from django.utils import timezone

from config import settings

NULLABLE = {"null": "True", "blank": "True"}
USER = settings.AUTH_USER_MODEL


class Entry(models.Model):
    title = models.CharField(max_length=200, verbose_name="Title")
    text = models.TextField(verbose_name="Text")
    image = models.ImageField(
        upload_to="diary_images/", verbose_name="Image", **NULLABLE
    )
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Date")
    is_public = models.BooleanField(default=False, verbose_name="Public")
    owner = models.ForeignKey(
        USER, on_delete=models.SET_NULL, verbose_name="Owner", **NULLABLE
    )

    # tag = models.CharField(max_length=50, verbose_name='Tag', **NULLABLE)

    def __str__(self):
        return f'"{self.title}" (added: {self.created_at})'

    class Meta:
        verbose_name = "entry"
        verbose_name_plural = "entries"
        ordering = ("created_at",)


# class Comment(models.Model):
#     entry = models.ForeignKey(Entry, on_delete=models.CASCADE, related_name='comments')
#     text = models.TextField()
#     created_at = models.DateTimeField(auto_now_add=True)
#
#     def __str__(self):
#         return f'Comment on {self.entry}: {self.text[:20]}...'

diary/forms.py
from django import forms
from django.forms import BooleanField

from diary.models import Entry


class StyleFormMixin(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input rounded"
            else:
                field.widget.attrs["class"] = "form-control rounded"


class EntryForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Entry
        # fields = '__all__'
        exclude = ("created_at", "owner")

diary/views.py
import random

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView)

from diary.forms import EntryForm
from diary.models import Entry
from diary.services import get_cache_for_entries_count


class Index(TemplateView):
    model = Entry
    template_name = "diary/index.html"
    extra_context = {
        "slogan": "Memont - memorize your moments.",
        "intro_text": "Be inspired by 'memonts' from community:",
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["total_entries_count"] = get_cache_for_entries_count
        context_data["public_entries_count"] = Entry.objects.filter(
            is_public=True
        ).count()
        context_data["personal_entries_count"] = Entry.objects.filter(
            is_public=False
        ).count()
        public_entries_list = list(Entry.objects.filter(is_public=True))
        random.shuffle(public_entries_list)
        context_data["public_entries_list"] = public_entries_list[:3]
        return context_data


class EntryListView(LoginRequiredMixin, ListView):
    model = Entry
    context_object_name = "entry_list"
    template_name = "diary/entry_list.html"

    def get_queryset(self):
        return Entry.objects.filter(owner=self.request.user)


class EntrySearchView(LoginRequiredMixin, ListView):
    model = Entry
    context_object_name = "entry_list"
    template_name = "diary/search_entries_list.html"

    def get_queryset(self):
        query = self.request.GET.get("query", "")
        if query:
            # Фильтруем записи по вхождению текста в заголовок или текст записи
            return Entry.objects.filter(
                Q(title__icontains=query) | Q(text__icontains=query),
                owner=self.request.user,
            )
        return Entry.objects.none()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["query"] = self.request.GET.get("query", "")
        return context


class EntryCreateView(LoginRequiredMixin, CreateView):
    model = Entry
    form_class = EntryForm
    success_url = reverse_lazy("diary:entry_list")
    extra_context = {"title": "Create entry"}

    def form_valid(self, form):
        new_entry = form.save(commit=False)
        new_entry.owner = self.request.user
        new_entry.save()
        return super().form_valid(form)


class EntryDetailView(LoginRequiredMixin, DetailView):
    model = Entry


class EntryUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Entry
    form_class = EntryForm
    success_url = reverse_lazy("diary:entry_list")
    extra_context = {"title": "Edit entry"}

    def test_func(self):
        entry = self.get_object()
        if self.request.user.is_staff:
            return True
        return self.request.user == entry.owner


class EntryDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Entry
    success_url = reverse_lazy("diary:entry_list")

    def test_func(self):
        entry = self.get_object()
        if self.request.user.is_superuser:
            return True
        return self.request.user == entry.owner

diary/templates/diary/includes/entries_list_style.html
<style>
    .row {
        display: flex; /* Используем Flexbox для размещения карточек */
        flex-wrap: wrap; /* Позволяем карточкам переноситься на следующую строку */
    }

    .custom-col {
        display: flex; /* Используем Flexbox внутри колонки */
        flex-direction: column; /* Устанавливаем вертикальное размещение элементов */
        justify-content: stretch; /* Позволяем карточкам занимать всю доступную высоту */
        padding: 1rem; /* Устанавливаем отступы между карточками */
    }

    .card {
        transition: background-color 0.3s ease, color 0.3s ease; /* Плавный переход */
        height: 100%; /* Устанавливаем фиксированную высоту карточки */
        width: 100%; /* Устанавливаем ширину на 100% */
        box-sizing: border-box; /* Учитываем отступы и границы в ширине */
    }

    .card:hover {
        background-color: #343a40; /* Цвет фона при наведении (темный) */
        color: white; /* Цвет текста при наведении (белый) */
    }

    .card-link {
        text-decoration: none; /* Убираем подчеркивание текста */
        color: inherit; /* Убираем изменение цвета текста по умолчанию */
        height: 100%; /* Устанавливаем высоту на 100% */
    }

    .card-body {
        display: flex;
        flex-direction: column; /* Устанавливаем вертикальное размещение элементов */
        flex-grow: 1; /* Позволяем телу карточки занимать доступное пространство */
    }

    .icon-small {
        font-size: 0.75rem; /* Уменьшаем размер иконки */
    }
    .highlight {
        background-color: rgba(180, 210, 250, 0.5); /* Полупрозрачный синий цвет для подсветки поиска */
    }
    .empty-message-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 75vh;
        text-align: center;
    }
</style>

diary/templates/diary/includes/nav_bar.html
{% load static %}
<div>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" style="padding-top: 20px; padding-bottom: 20px;">
    <div class="container-fluid">
        <a class="navbar-brand ms-3" href="{% url 'diary:index' %}" style="margin-right: 40px;">
            <img src="{% static 'Memont_logo_edit_final_v2.svg' %}" alt="M E M O N T" style="height: 28px;"/>
        </a>
            {% if user.is_authenticated %}
            <div class="button-container">
                <a class="btn btn-outline-secondary" href="{% url 'diary:entry_list' %}" title="List entries"
                   style="border-radius: 50%; width: 45px; height: 45px;
                   display: flex; align-items: center; justify-content: center; padding: 0;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">
                        <circle cx="4" cy="6" r="0.7"></circle>
                        <line x1="8" y1="6" x2="18" y2="6"></line>
                        <circle cx="4" cy="12" r="0.7"></circle>
                        <line x1="8" y1="12" x2="18" y2="12"></line>
                        <circle cx="4" cy="18" r="0.7"></circle>
                        <line x1="8" y1="18" x2="18" y2="18"></line>
                    </svg>
                </a>
            </div>
            <div class="container">
                <a class="btn btn-outline-secondary" href="{% url 'diary:entry_create' %}" title="Add entry"
                   style="border-radius: 50%; width: 45px; height: 45px;
                   display: flex; align-items: center; justify-content: center; padding: 0;">
                    <i class="fas fa-plus" style="font-size: 1rem; margin: 0;"></i>
                </a>
            </div>
            {% endif %}
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0"></ul>
                <form class="d-flex me-4" role="search" action="{% url 'diary:entry_search' %}" method="get"
                      style="position: relative;">
                    <input class="form-control" name="query" type="search"
                           placeholder="Type to search" aria-label="Search"
                           style="border-radius: 25px; padding-right: 30px;">
                    <button type="submit" aria-label="Search"
                            style="background: none; border: none; padding: 0;
                            position: absolute; right: 10px; top: 50%; transform: translateY(-50%);">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                             stroke-linecap="round" stroke-linejoin="round" stroke-width="1" role="img"
                             viewBox="0 0 24 24">
                            <title>Go!</title>
                            <circle cx="10.5" cy="10.5" r="7"/>
                            <path d="M21 21l-5.2-5.2"/>
                        </svg>
                    </button>
                </form>
                {% if user.is_authenticated %}
                <a class="btn btn-outline-secondary ms-2 me-2"
                   style="border-radius: 25px;" href="{% url 'users:profile' %}">Profile</a>
                <form method="post" action="{% url 'users:logout' %}">
                    {% csrf_token %}
                    <button class="btn btn-outline-secondary me-3"
                            style="border-radius: 25px;" type="submit">Logout
                    </button>
                </form>
                {% else %}
                <a class="btn btn-outline-secondary ms-2 me-2"
                   style="border-radius: 25px;" href="{% url 'users:register' %}">Signup</a>
                <a class="btn btn-outline-secondary me-3"
                   style="border-radius: 25px;" href="{% url 'users:login' %}">Login</a>
                {% endif %}
            </div>
            <div class="date-display"
                 style="position: absolute; left: 50%; transform: translateX(-50%); color: white; margin-top: 10px;">
                {% now 'l, F j, Y' %}
            </div>
        </div>
    </nav>
</div>